// Gerado por scripts/update-bank-icons.mjs a partir do react-bancos (MIT, commit 03a805042d7f) — não editar à mão.
// Os logos são marcas de seus titulares, usados só para identificar as instituições.
export type BankIconKind = 'bank' | 'card' | 'other';

export interface BankIcon {
  /** Nome do arquivo em public/banks/<slug>.svg */
  slug: string;
  name: string;
  /** Código de compensação do Bacen, quando houver. */
  compe: string | null;
  /** Cor de fundo do ícone (#RRGGBB). */
  color: string | null;
  kind: BankIconKind;
}

export const BANK_ICONS: readonly BankIcon[] = [
  { slug: "99pay", name: "99Pay", compe: null, color: "#FEDF00", kind: 'other' },
  { slug: "abcbrasil", name: "Banco ABC Brasil", compe: "246", color: "#1E1E1E", kind: 'bank' },
  { slug: "adyen", name: "Adyen", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "agibank", name: "Agibank", compe: "121", color: "#266BFF", kind: 'bank' },
  { slug: "ailos", name: "Ailos", compe: "085", color: "#FFFFFF", kind: 'bank' },
  { slug: "alelo", name: "Alelo", compe: null, color: "#008060", kind: 'other' },
  { slug: "almah", name: "Almah Conta", compe: null, color: "#1C1444", kind: 'bank' },
  { slug: "amazon", name: "Cartão Amazon", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "amazonprime", name: "Cartão Amazon Prime", compe: null, color: "#0779FF", kind: 'card' },
  { slug: "americanas", name: "Cartão Americanas", compe: null, color: "#F80032", kind: 'card' },
  { slug: "amex", name: "American Express", compe: null, color: "#006FCF", kind: 'card' },
  { slug: "applepay", name: "Apple Pay", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "arbi", name: "Banco Arbi", compe: "213", color: "#FFFFFF", kind: 'bank' },
  { slug: "artta", name: "ARTTA", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "asaas", name: "Asaas", compe: "461", color: "#0038E5", kind: 'bank' },
  { slug: "atacadao", name: "Cartão Atacadão", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "avenue", name: "Avenue", compe: null, color: "#002820", kind: 'bank' },
  { slug: "azul", name: "Cartão Azul", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "bancodaamazonia", name: "Banco da Amazônia", compe: "003", color: "#003C2D", kind: 'bank' },
  { slug: "bancodobrasil", name: "Banco do Brasil", compe: "001", color: "#FEE60E", kind: 'bank' },
  { slug: "bancodobrasilinfinite", name: "Ourocard Visa Infinite", compe: null, color: "#0D0D0D", kind: 'card' },
  { slug: "bancodonordeste", name: "Banco do Nordeste", compe: "004", color: "#A6193C", kind: 'bank' },
  { slug: "bancomaster", name: "Banco Master", compe: "243", color: "#0D2A5C", kind: 'bank' },
  { slug: "banese", name: "Banese", compe: "047", color: "#00622A", kind: 'bank' },
  { slug: "banestes", name: "Banestes", compe: "021", color: "#004B8D", kind: 'bank' },
  { slug: "bankly", name: "Bankly", compe: "332", color: "#347BFF", kind: 'bank' },
  { slug: "bankofamerica", name: "Bank of America Merrill Lynch", compe: "755", color: "#FFFFFF", kind: 'bank' },
  { slug: "banpara", name: "Banpará", compe: "037", color: "#EA1C24", kind: 'bank' },
  { slug: "banrisul", name: "Banrisul", compe: "041", color: "#010050", kind: 'bank' },
  { slug: "banrisulinfinite", name: "Banrisul Visa Infinite", compe: null, color: "#0D0D0D", kind: 'card' },
  { slug: "bari", name: "Banco Bari", compe: null, color: "#000000", kind: 'bank' },
  { slug: "beesbank", name: "BEES Bank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "binance", name: "Binance", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "bitget", name: "Bitget", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "bitso", name: "Bitso", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "bkbank", name: "BK Bank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "bmg", name: "Banco BMG", compe: "318", color: "#F26321", kind: 'bank' },
  { slug: "bmp", name: "BMP Money Plus", compe: "274", color: "#0D0D12", kind: 'bank' },
  { slug: "bnpparibas", name: "Banco BNP Paribas Brasil", compe: "752", color: "#00915A", kind: 'bank' },
  { slug: "bradesco", name: "Bradesco", compe: "237", color: "#CF2032", kind: 'bank' },
  { slug: "bradescoinfinite", name: "Bradesco Visa Infinite", compe: null, color: "#101010", kind: 'card' },
  { slug: "brb", name: "BRB — Banco de Brasília", compe: "070", color: "#173E7D", kind: 'bank' },
  { slug: "brex", name: "Brex", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "bs2", name: "Banco BS2", compe: "218", color: "#3333CC", kind: 'bank' },
  { slug: "btgpactual", name: "BTG Pactual", compe: "208", color: "#001E61", kind: 'bank' },
  { slug: "btgultrablue", name: "BTG Pactual Ultrablue", compe: null, color: "#0A5FD9", kind: 'card' },
  { slug: "bv", name: "Banco BV", compe: "655", color: "#5776D0", kind: 'bank' },
  { slug: "bybit", name: "Bybit", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "c6bank", name: "C6 Bank", compe: "336", color: "#000000", kind: 'bank' },
  { slug: "c6carbon", name: "C6 Carbon", compe: null, color: "#1C1C1C", kind: 'card' },
  { slug: "c6global", name: "C6 Global", compe: null, color: "#0A2540", kind: 'bank' },
  { slug: "caixa", name: "Caixa Econômica Federal", compe: "104", color: "#ECECFB", kind: 'bank' },
  { slug: "caju", name: "Caju", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "capitual", name: "Capitual", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "carrefour", name: "Cartão Carrefour", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "casasbahia", name: "Cartão Casas Bahia", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "cashapp", name: "Cash App", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "cea", name: "Cartão C&A", compe: null, color: "#000000", kind: 'card' },
  { slug: "celcoin", name: "Celcoin", compe: "509", color: "#7664FA", kind: 'bank' },
  { slug: "citibank", name: "Citibank", compe: "745", color: "#255BE3", kind: 'bank' },
  { slug: "cloudwalk", name: "CloudWalk", compe: "542", color: "#000000", kind: 'bank' },
  { slug: "coinbase", name: "Coinbase", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "colombo", name: "Cartão Colombo", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "contaazul", name: "Conta Azul", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "contasimples", name: "Conta Simples", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "contbank", name: "Contbank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "cora", name: "Cora", compe: "403", color: "#FE3E6D", kind: 'bank' },
  { slug: "credisis", name: "CrediSIS", compe: "097", color: "#FFFFFF", kind: 'bank' },
  { slug: "creditas", name: "Creditas", compe: "342", color: "#8EDB00", kind: 'bank' },
  { slug: "cresol", name: "Cresol", compe: "133", color: "#EF8124", kind: 'bank' },
  { slug: "cryptocom", name: "Crypto.com", compe: null, color: "#0A0E1A", kind: 'other' },
  { slug: "daycoval", name: "Banco Daycoval", compe: "707", color: "#001C55", kind: 'bank' },
  { slug: "decolar", name: "Cartão Decolar", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "deutsche", name: "Deutsche Bank Brasil", compe: "487", color: "#0018A8", kind: 'bank' },
  { slug: "digimais", name: "Banco Digimais", compe: "654", color: "#171B3D", kind: 'bank' },
  { slug: "digio", name: "Digio", compe: "335", color: "#23292E", kind: 'bank' },
  { slug: "dinersclub", name: "Diners Club", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "discover", name: "Discover", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "dock", name: "Dock", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "edenred", name: "Edenred", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "efibank", name: "Efí Bank", compe: "364", color: "#F37124", kind: 'bank' },
  { slug: "fibra", name: "Banco Fibra", compe: "224", color: "#082A4D", kind: 'bank' },
  { slug: "fidelity", name: "Fidelity", compe: null, color: "#EE2722", kind: 'bank' },
  { slug: "flash", name: "Flash Benefícios", compe: null, color: "#FE2B8F", kind: 'other' },
  { slug: "googlepay", name: "Google Pay", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "grafeno", name: "Grafeno", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "havan", name: "Cartão Havan", compe: null, color: "#00275E", kind: 'card' },
  { slug: "hipercard", name: "Hipercard", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "honda", name: "Banco Honda", compe: null, color: "#DA251D", kind: 'bank' },
  { slug: "ifood", name: "iFood Benefícios", compe: null, color: "#EA1D2C", kind: 'other' },
  { slug: "ifoodpago", name: "iFood Pago", compe: null, color: "#EA1D2C", kind: 'bank' },
  { slug: "inbursa", name: "Banco Inbursa", compe: "012", color: "#012148", kind: 'bank' },
  { slug: "industrialdobrasil", name: "Banco Industrial do Brasil", compe: "604", color: "#001D5D", kind: 'bank' },
  { slug: "infinitepay", name: "InfinitePay", compe: null, color: "#171527", kind: 'bank' },
  { slug: "inter", name: "Banco Inter", compe: "077", color: "#FF7A00", kind: 'bank' },
  { slug: "interglobal", name: "Inter Global", compe: null, color: "#101010", kind: 'bank' },
  { slug: "itau", name: "Itaú Unibanco", compe: "341", color: "#FE6100", kind: 'bank' },
  { slug: "itaublack", name: "Itaú Black", compe: null, color: "#141414", kind: 'card' },
  { slug: "itaupersonnalite", name: "Itaú Personnalité", compe: null, color: "#0C2B52", kind: 'bank' },
  { slug: "itautheone", name: "Itaú Personnalité The One", compe: null, color: "#101010", kind: 'card' },
  { slug: "itauuniclass", name: "Itaú Uniclass", compe: null, color: "#1C4F82", kind: 'bank' },
  { slug: "iugu", name: "iugu", compe: "401", color: "#1B1B1B", kind: 'other' },
  { slug: "jcb", name: "JCB", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "kabum", name: "Cartão KaBuM!", compe: null, color: "#000000", kind: 'card' },
  { slug: "klarna", name: "Klarna", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "klavi", name: "Klavi", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "latampass", name: "Cartão LATAM Pass", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "leader", name: "Cartão Leader", compe: null, color: "#ED1C24", kind: 'card' },
  { slug: "letsbank", name: "LetsBank", compe: "630", color: "#0D0D0D", kind: 'bank' },
  { slug: "linker", name: "Linker", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "livelo", name: "Cartão Livelo", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "maestro", name: "Maestro", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "magalupay", name: "MagaluPay", compe: "396", color: "#FFFFFF", kind: 'bank' },
  { slug: "marisa", name: "Cartão Marisa", compe: null, color: "#EC008C", kind: 'card' },
  { slug: "mastercard", name: "Mastercard", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "meliuz", name: "Cartão Méliuz", compe: null, color: "#FD9CBF", kind: 'card' },
  { slug: "mercadobitcoin", name: "Mercado Bitcoin", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "mercadopago", name: "Mercado Pago", compe: "323", color: "#00BCFF", kind: 'bank' },
  { slug: "mercantil", name: "Banco Mercantil", compe: "389", color: "#1526FF", kind: 'bank' },
  { slug: "mizuho", name: "Banco Mizuho do Brasil", compe: "370", color: "#37498B", kind: 'bank' },
  { slug: "modobank", name: "Modobank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "morganstanley", name: "Banco Morgan Stanley", compe: "066", color: "#FFFFFF", kind: 'bank' },
  { slug: "mufg", name: "Banco MUFG Brasil", compe: "456", color: "#E30613", kind: 'bank' },
  { slug: "multiplobank", name: "Múltiplo Bank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "n26", name: "N26", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "neon", name: "Neon", compe: "735", color: "#00A8EF", kind: 'bank' },
  { slug: "neteller", name: "Neteller", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "next", name: "Next", compe: null, color: "#1E3C3C", kind: 'bank' },
  { slug: "ngcash", name: "NG.CASH", compe: null, color: "#000000", kind: 'bank' },
  { slug: "nomad", name: "Nomad", compe: null, color: "#FFCE04", kind: 'bank' },
  { slug: "nubank", name: "Nubank", compe: "260", color: "#820AD1", kind: 'bank' },
  { slug: "nubankcroma", name: "Nubank Croma", compe: null, color: "#F2F0EF", kind: 'card' },
  { slug: "nubankultravioleta", name: "Nubank Ultravioleta", compe: null, color: "#2B0A4D", kind: 'card' },
  { slug: "okx", name: "OKX", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "omiecash", name: "Omie.Cash", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "omni", name: "Omni Banco", compe: "613", color: "#FFFFFF", kind: 'bank' },
  { slug: "onfly", name: "Onfly", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "original", name: "Banco Original", compe: "212", color: "#18AD47", kind: 'bank' },
  { slug: "originalblack", name: "Banco Original Black", compe: null, color: "#0A0A0A", kind: 'card' },
  { slug: "originalgold", name: "Banco Original Gold", compe: null, color: "#B6903F", kind: 'card' },
  { slug: "originalinternational", name: "Banco Original International", compe: null, color: "#145C30", kind: 'bank' },
  { slug: "originalplatinum", name: "Banco Original Platinum", compe: null, color: "#9A9A9D", kind: 'card' },
  { slug: "orionpay", name: "OrionPay", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "ourinvest", name: "Banco Ourinvest", compe: "712", color: "#15252D", kind: 'bank' },
  { slug: "outros", name: "Outros", compe: null, color: "#9AA0A6", kind: 'other' },
  { slug: "pagarme", name: "Pagar.me", compe: null, color: "#00AF55", kind: 'other' },
  { slug: "pagbank", name: "PagBank", compe: "290", color: "#1BB99A", kind: 'bank' },
  { slug: "pan", name: "Banco Pan", compe: "623", color: "#363636", kind: 'bank' },
  { slug: "paulista", name: "Banco Paulista", compe: "611", color: "#FFFFFF", kind: 'bank' },
  { slug: "paycash", name: "PayCash", compe: null, color: "#1C3256", kind: 'other' },
  { slug: "payoneer", name: "Payoneer", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "paypal", name: "PayPal", compe: null, color: "#003087", kind: 'other' },
  { slug: "pernambucanas", name: "Cartão Pernambucanas", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "picpay", name: "PicPay", compe: "380", color: "#11C76F", kind: 'bank' },
  { slug: "picpayblack", name: "PicPay Black", compe: null, color: "#101010", kind: 'card' },
  { slug: "pinbank", name: "PinBank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "pine", name: "Banco Pine", compe: "643", color: "#661739", kind: 'bank' },
  { slug: "pluggy", name: "Pluggy", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "pluxee", name: "Pluxee", compe: null, color: "#221C46", kind: 'other' },
  { slug: "polishop", name: "Cartão Polishop", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "ponto", name: "Cartão Ponto", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "porto", name: "Porto", compe: null, color: "#00A1FC", kind: 'bank' },
  { slug: "portoblack", name: "Porto Bank Black", compe: null, color: "#101010", kind: 'card' },
  { slug: "portoinfinite", name: "Porto Bank Infinite", compe: null, color: "#0D0D0D", kind: 'card' },
  { slug: "qitech", name: "QI Tech", compe: "329", color: "#101828", kind: 'bank' },
  { slug: "qive", name: "Qive", compe: null, color: "#0F1115", kind: 'other' },
  { slug: "qualitybank", name: "Quality Digital Bank", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "queroquero", name: "Cartão Quero-Quero", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "rabobank", name: "Banco Rabobank", compe: "747", color: "#283A93", kind: 'bank' },
  { slug: "rappicard", name: "Cartão RappiCard", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "recargapay", name: "RecargaPay", compe: null, color: "#053E6E", kind: 'other' },
  { slug: "rendimento", name: "Banco Rendimento", compe: "633", color: "#0A1D6F", kind: 'bank' },
  { slug: "renner", name: "Cartão Renner", compe: null, color: "#D72027", kind: 'card' },
  { slug: "revolut", name: "Revolut", compe: null, color: "#000000", kind: 'bank' },
  { slug: "riachuelo", name: "Cartão Riachuelo", compe: null, color: "#0C2E2D", kind: 'card' },
  { slug: "rico", name: "Rico", compe: null, color: "#010042", kind: 'bank' },
  { slug: "ripio", name: "Ripio", compe: null, color: "#690ED8", kind: 'other' },
  { slug: "robinhood", name: "Robinhood", compe: null, color: "#000000", kind: 'bank' },
  { slug: "safra", name: "Banco Safra", compe: "422", color: "#00003C", kind: 'bank' },
  { slug: "safrainfiniteiridium", name: "Safra Visa Infinite Metal Iridium", compe: null, color: "#8F9296", kind: 'card' },
  { slug: "samsung", name: "Cartão Samsung", compe: null, color: "#000000", kind: 'card' },
  { slug: "santander", name: "Santander", compe: "033", color: "#FE0000", kind: 'bank' },
  { slug: "santanderelite", name: "Santander Elite", compe: null, color: "#9A9A9D", kind: 'card' },
  { slug: "santanderunique", name: "Santander Unique", compe: null, color: "#101010", kind: 'card' },
  { slug: "schwab", name: "Charles Schwab", compe: null, color: "#00A0DF", kind: 'bank' },
  { slug: "sicoob", name: "Sicoob", compe: "756", color: "#003641", kind: 'bank' },
  { slug: "sicoobverth", name: "Sicoob Verth", compe: null, color: "#0F4D2E", kind: 'bank' },
  { slug: "sicredi", name: "Sicredi", compe: "748", color: "#3FA110", kind: 'bank' },
  { slug: "sicrediinfinite", name: "Sicredi Visa Infinite", compe: null, color: "#16352A", kind: 'card' },
  { slug: "sisprime", name: "Sisprime do Brasil", compe: "084", color: "#FFFFFF", kind: 'bank' },
  { slug: "skrill", name: "Skrill", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "socgen", name: "Banco Société Générale Brasil", compe: "366", color: "#FFFFFF", kind: 'bank' },
  { slug: "sofisa", name: "Banco Sofisa", compe: "637", color: "#17B497", kind: 'bank' },
  { slug: "square", name: "Square", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "squid", name: "Squid", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "starkbank", name: "Stark Bank", compe: null, color: "#1D2732", kind: 'bank' },
  { slug: "stellantis", name: "Banco Stellantis", compe: null, color: "#243882", kind: 'bank' },
  { slug: "stone", name: "Stone", compe: "197", color: "#0DB14B", kind: 'bank' },
  { slug: "stripe", name: "Stripe", compe: null, color: "#635BFF", kind: 'other' },
  { slug: "sulcredi", name: "Sulcredi", compe: null, color: "#FFFFFF", kind: 'bank' },
  { slug: "sumitomo", name: "Banco Sumitomo Mitsui Brasileiro", compe: "464", color: "#FFFFFF", kind: 'bank' },
  { slug: "sumup", name: "SumUp", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "swile", name: "Swile", compe: null, color: "#000000", kind: 'other' },
  { slug: "ticket", name: "Ticket", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "ton", name: "Ton", compe: null, color: "#0DEA4A", kind: 'bank' },
  { slug: "topazio", name: "Banco Topázio", compe: "082", color: "#50C3C7", kind: 'bank' },
  { slug: "toro", name: "Toro Investimentos", compe: "352", color: "#000000", kind: 'bank' },
  { slug: "toyota", name: "Banco Toyota", compe: "387", color: "#EB0A1E", kind: 'bank' },
  { slug: "transfeera", name: "Transfeera", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "tribanco", name: "Tribanco", compe: "634", color: "#00336D", kind: 'bank' },
  { slug: "unicred", name: "Unicred", compe: "136", color: "#004A35", kind: 'bank' },
  { slug: "unionpay", name: "UnionPay", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "uniprime", name: "Uniprime", compe: "099", color: "#FFFFFF", kind: 'bank' },
  { slug: "uzzipay", name: "UzziPay", compe: null, color: "#53A000", kind: 'bank' },
  { slug: "venmo", name: "Venmo", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "visa", name: "Visa", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "visaelectron", name: "Visa Electron", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "volkswagen", name: "Banco Volkswagen", compe: "393", color: "#001E50", kind: 'bank' },
  { slug: "vrbeneficios", name: "VR Benefícios", compe: null, color: "#00A413", kind: 'other' },
  { slug: "warren", name: "Warren Investimentos", compe: "371", color: "#E24324", kind: 'bank' },
  { slug: "willbank", name: "Will Bank", compe: null, color: "#FFD900", kind: 'bank' },
  { slug: "wise", name: "Wise", compe: null, color: "#9FE870", kind: 'bank' },
  { slug: "xp", name: "XP", compe: "348", color: "#000000", kind: 'bank' },
  { slug: "xpglobal", name: "XP Global", compe: null, color: "#101010", kind: 'bank' },
  { slug: "zelle", name: "Zelle", compe: null, color: "#FFFFFF", kind: 'other' },
  { slug: "zema", name: "Cartão Zema", compe: null, color: "#FFFFFF", kind: 'card' },
  { slug: "zemobank", name: "Zemo Bank", compe: null, color: "#001041", kind: 'bank' },
  { slug: "zrobank", name: "Zro Bank", compe: null, color: "#252F59", kind: 'bank' },
];
